query CartCurrentQuery {
    cartCurrent {
        ...CartFragment
    }
}

mutation setProductToCart($input: CartAddProductInput!) {
    cartCurrentSetProduct(input: $input) {
        data {
            ...CartFragment
        }
    }
}

mutation removeProductFromCart($input: CartRemoveProductInput!) {
    cartCurrentRemoveProduct(input: $input) {
        data {
            ...CartFragment
        }
    }
}

fragment CartFragment on UserCart {
    id
    contents {
        ...CartContentFragment
    }
    tallies {
        priceCents
        fullPriceCents
        discountCents
        provider
    }
    completedAt
    pickedProvider
}

fragment CartContentFragment on CartContent {
    id
    quantity
    createdAt
    ... on CartNoteProduct {
        note
    }
    ... on CartAggregateProduct {
        aggregate {
            id
            name
            imageUrl
            createdAt
            price(format: MINIMUM)
            ingredients {
                ...ProductCardFragment
            }
        }
    }
    ... on CartProviderProduct {
        product {
            ...ProductCardFragment
        }
    }
}
