query CartCurrentQuery($price: PriceFilter!) {
    cartCurrent {
        ...CartFragment
    }
}

mutation setProductToCart($input: CartAddProductInput!, $price: PriceFilter!) {
    cartCurrentSetProduct(input: $input) {
        data {
            ...CartFragment
        }
    }
}

mutation removeProductFromCart($input: CartRemoveProductInput!, $price: PriceFilter!) {
    cartCurrentRemoveProduct(input: $input) {
        data {
            ...CartFragment
        }
    }
}

fragment CartFragment on UserCart {
    id
    contents {
        ...CartContentFragment
    }
    tallies {
        priceCents
        fullPriceCents
        discountCents
        providerInfo {
            provider
            logoUrl
        }
    }
    completedAt
    pickedProvider
}

fragment CartContentFragment on CartContent {
    __typename
    id
    quantity
    createdAt
    ... on CartNoteProduct {
        note
    }
    ... on CartAggregateProduct {
        aggregate {
            id
            name
            imageUrl
            createdAt
            price(format: $price)
            ingredients {
                ...ProductCardFragment
            }
        }
    }
    ... on CartProviderProduct {
        product {
            ...ProductCardFragment
        }
    }
}
