query FullProductQuery($provider: Provider!, $productId: String!) {
    proProduct(provider: $provider, productId: $productId) {
        ...FullProductFragment
    }
}

fragment FullProductFragment on WggProduct {
    id
    name
    description {
        text
        textType
    }
    priceInfo {
        displayPrice
        originalPrice
        unitPrice {
            unit
            price
        }
    }
    saleInformation {
        label
        additionalLabel
        saleValidity {
            validFrom
            validUntil
        }
        saleType {
            __typename
        }
    }
    unitQuantity {
        unit
        amount
    }
    available
    imageUrls
    ingredients {
        name
    }
    nutritional {
        infoUnit
        items {
            name
            value
            subValues {
                name
                value
            }
        }
    }
    allergyInfo {
        name
        contains
    }
    additionalItems {
        itemType
        text
        textType
    }
    decorators {
        ...FullDecorator
    }
    providerInfo {
        provider
        logoUrl
    }
}

fragment FullDecorator on WggDecorator {
    __typename
    ... on FreshLabel {
        daysFresh
    }
    ... on UnavailableItem {
        reason
        explanationShort
        explanationLong
        replacements {
            ...ProductCardFragment
        }
    }
    ... on PrepTime {
        timeMinutes
    }
    ... on NumberOfServings {
        amount
    }
    ... on MoreButton {
        images
    }
}