query getAggregateIngredientsModal($first: Int, $after: String, $filters: IngredientQueryFilter, $price: PriceFilter!) {
    aggregateIngredients(first: $first, after: $after, filters: $filters) {
        edges {
            cursor
            node {
                ...PartialFullAggregateFragment
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
        }
        totalCount
    }
}

fragment PartialFullAggregateFragment on AggregateIngredient {
    ...AggregateCardFragment
    ingredients {
        id
        providerInfo {
            provider
        }
    }
}

fragment AddProductModalFragment on WggProduct {
    id
    providerInfo {
        provider
    }
}