fragment AggregateCardFragment on AggregateIngredient {
    __typename
    id
    name
    imageUrl
    createdAt
    price(format: $price)
}

fragment AggregateFullFragment on AggregateIngredient {
    ... AggregateCardFragment
    ingredients {
        ...ProductCardFragment
    }
}