fragment AggregateCardFragment on AggregateIngredient {
    __typename
    id
    name
    imageUrl
    createdAt
    sales {
        label
        saleType {
            __typename
        }
    }
    price(format: $price)
}

fragment AggregateFullFragment on AggregateIngredient {
    ... AggregateCardFragment
    ingredients {
        ...ProductCardFragment
    }
}