mutation createAggregateProduct($input: AggregateCreateInput!, $price: PriceFilter!) {
    aggregateIngredientCreate(input: $input) {
        data {
            ...AggregateFullFragment
        }
    }
}
