mutation setProductToCart($input: CartAddProductInput!) {
    cartCurrentSetProduct(input: $input) {
        data {
            ...CartFragment
        }
    }
}

mutation removeProductFromCart($input: CartRemoveProductInput!) {
    cartCurrentRemoveProduct(input: $input) {
        data {
            ...CartFragment
        }
    }
}

fragment ProductCardFragment on WggSearchProduct {
    id
    name
    displayPrice
    fullPrice
    imageUrl
    available
    unitQuantity {
        unit
        amount
    }
    unitPrice {
        unit
        price
    }
    decorators {
        __typename
        ... on SaleLabel {
            text
        }
        ... on SaleValidity {
            validFrom
            validUntil
        }
    }
    provider
}
