query getAllPromotions {
    proPromotions(provider: PICNIC) {
        id
        name
        limitedItems {
            ... on WggSearchProduct {
                ...ProductCardFragment
            }
        }
    }
    proSearchAll(query: "sun") {
        ...ProductCardFragment
    }
}
