query getAllPromotions {
    proSearchAll(query: "banaan") {
        id
        name
        imageUrl
        provider
        displayPrice
        unitQuantity {
            unit
            amount
        }
    }
}
