query getSaleSublist($id: String!, $provider: Provider!) {
    proPromotionsSublist(provider: $provider, sublistId: $id) {
        ...SaleGroupCompleteFragment
    }
}

fragment SaleGroupCompleteFragment on WggSaleGroupComplete {
    id
    name
    imageUrls
    items {
        ...ProductCardFragment
    }
    saleDescription
    saleInfo {
        label
        additionalLabel
        saleValidity {
            validFrom
            validUntil
        }
        saleType {
            __typename
        }
    }
    providerInfo {
        provider
        logoUrl
    }
}
