[package]
name = "wgg_providers"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.60"
thiserror = "1.0.32"
tracing = "0.1.36"
itertools = "0.10"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"

# Web
tower = "0.4.13"

time = { version = "0.3", features = ["parsing", "serde", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.82"
reqwest = { version = "0.11.11", features = ["json", "cookies", "rustls-tls", "gzip"] }

wgg_picnic = { path = "../wgg_picnic" }
wgg_jumbo = { path = "../wgg_jumbo" }

[dev-dependencies]
static_init = "1"
pretty_assertions = "1.2"
tempfile = "3"
const_format = "0.2.13"

