query getAggregateIngredients($first: Int, $after: String, $filters: IngredientQueryFilter, $price: PriceFilter!) {
    aggregateIngredients(first: $first, after: $after, filters: $filters) {
        edges {
            cursor
            node {
                ...AggregateCardFragment
                price(format: $price)
            }
        }
        totalCount
    }
}