fragment ProductCardFragment on WggSearchProduct {
    __typename
    id
    name
    displayPrice
    fullPrice
    imageUrl
    available
    saleInformation {
         label
         additionalLabel
         saleValidity {
            validFrom
            validUntil
         }
         saleType {
            __typename
         }
    }
    unitQuantity {
        unit
        amount
    }
    unitPrice {
        unit
        price
    }
    decorators {
        ...ProductCardDecoratorFragment
    }
    providerInfo {
        provider
        logoUrl
    }
}

fragment ProductCardDecoratorFragment on WggDecorator {
    __typename
    ... on UnavailableItem {
        reason
        explanationShort
        explanationLong
        replacements {
            id
            name
            imageUrl
        }
    }
}

fragment SaleTypeNameFragment on SaleType {
    __typename
}