fragment ProductCardFragment on WggSearchProduct {
    id
    name
    displayPrice
    fullPrice
    imageUrl
    available
    unitQuantity {
        unit
        amount
    }
    unitPrice {
        unit
        price
    }
    decorators {
        ...ProductCardDecoratorFragment
    }
    providerInfo {
        provider,
        logoUrl
    }
}

fragment ProductCardDecoratorFragment on WggDecorator {
    __typename
    ... on SaleLabel {
        text
    }
    ... on SaleValidity {
        validFrom
        validUntil
    }
    ... on UnavailableItem {
        reason
        explanationShort
        explanationLong
        replacements {
            id
            name
            imageUrl
        }
    }
}
