fragment ProductCardFragment on WggSearchProduct {
    __typename
    id
    name
    priceInfo {
        displayPrice
        originalPrice
        unitPrice {
            unit
            price
        }
    }
    imageUrl
    unavailableDetails {
        reason
        explanationShort
        explanationLong
        replacements {
            id
            name
            imageUrl
        }
    }
    saleInformation {
         label
         additionalLabel
         saleValidity {
            validFrom
            validUntil
         }
         saleType {
            __typename
         }
    }
    unitQuantity {
        unit
        amount
    }
    decorators {
        ...ProductCardDecoratorFragment
    }
    providerInfo {
        provider
        logoUrl
    }
}

fragment ProductCardDecoratorFragment on WggDecorator {
    __typename
}

fragment SaleTypeNameFragment on SaleType {
    __typename
}