query getAggregateIngredient($id: Int!, $price: PriceFilter!) {
    aggregateIngredient(id: $id) {
        ...AggregateCardFragment
        ingredients {
            ...ProductCardFragment
        }
    }
}

mutation deleteAggregateIngredient($id: Int!) {
    aggregateIngredientDelete(ids: [$id]) {
        deleted
    }
}