//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agg_ingredients_link::Entity")]
    AggIngredientsLink,
    #[sea_orm(has_many = "super::agg_ingredients_links::Entity")]
    AggIngredientsLinks,
}

impl Related<super::agg_ingredients_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AggIngredientsLink.def()
    }
}

impl Related<super::agg_ingredients_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AggIngredientsLinks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
