//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "providers"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AggIngredientsLinks,
    Cart,
    CartContentsProvider,
    CartTally,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AggIngredientsLinks => Entity::has_many(super::agg_ingredients_links::Entity).into(),
            Self::Cart => Entity::has_many(super::cart::Entity).into(),
            Self::CartContentsProvider => Entity::has_many(super::cart_contents_provider::Entity).into(),
            Self::CartTally => Entity::has_many(super::cart_tally::Entity).into(),
        }
    }
}

impl Related<super::agg_ingredients_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AggIngredientsLinks.def()
    }
}

impl Related<super::cart_contents_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CartContentsProvider.def()
    }
}

impl Related<super::cart_tally::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CartTally.def()
    }
}

impl Related<super::cart::Entity> for Entity {
    fn to() -> RelationDef {
        super::cart_tally::Relation::Cart.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cart_tally::Relation::Providers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
