query getFilteredPromotions($after: String, $first: Int, $filters: PromotionsFilter!) {
    proPromotions(after: $after, first: $first, filters: $filters) {
        totalCount
        edges {
            cursor
            node {
                ...SaleCategoryFragment
            }
        }
    }
}

fragment SaleCategoryFragment on WggSaleCategory {
    __typename
    id
    name
    imageUrls
    complete
    providerInfo {
        provider
        logoUrl
    }
    items {
        __typename
        id
        ... on WggSaleGroupLimited {
            # Note we'd like to use ...SaleGroupFragment here, but for some reason that breaks caching (when returning a cached result only `__typename` and `id`
            # are then included). By directly embedding this that issue is prevented.
            id
            name
            imageUrls
            saleDescription
            saleInfo {
                label
                additionalLabel
                saleValidity {
                    validFrom
                    validUntil
                }
                saleType {
                    __typename
                }
            }
            providerInfo {
                provider
                logoUrl
            }
        }
        ... on WggSearchProduct {
            ...ProductCardFragment
        }
    }
}

fragment SaleGroupFragment on WggSaleGroupLimited {
    id
    name
    imageUrls
    saleDescription
    saleInfo {
        label
        additionalLabel
        saleValidity {
            validFrom
            validUntil
        }
        saleType {
            __typename
        }
    }
    providerInfo {
        provider
        logoUrl
    }
}
