query getFilteredPromotions($after: String, $first: Int, $filters: PromotionsFilter!) {
    proPromotions(after: $after, first: $first, filters: $filters) {
        totalCount
        edges {
            cursor
            node {
                ...SaleCategoryFragment
            }
        }
    }
}

fragment SaleCategoryFragment on WggSaleCategory {
    __typename
    id
    name
    imageUrls
    complete
    providerInfo {
        provider
        logoUrl
    }
    items {
        __typename
        id
        ... on WggSaleGroupLimited {
            ...SaleGroupFragment
        }
        ... on WggSearchProduct {
            ...ProductCardFragment
        }
    }
}

fragment SaleGroupFragment on WggSaleGroupLimited {
    __typename
    id
    name
    imageUrls
    decorators {
        ...ProductCardDecoratorFragment
        ... on SaleDescription {
            text
        }
        ... on SaleValidity {
            validFrom
            validUntil
        }
    }
}
